= m-creations fork of Apache Isis

This repo contains a fork of Apache Isis with a small number of
patches which we need for our daily work. We rebase regularly on the
latest release version and create a release of our own with a suffix
`-mcN` where `N` is a number starting with `1`,
e.g. `isis-1.13.0-mc1`.

Apache Isis' master branch can be found in our `upstream` branch.

== Patch: Allow JsonNode properties to be treated as values
    
We need JSON action arguments and response attributes in some cases:
especially for being able to port older services to Apache Isis while
keeping the structure of the JSON which is posted by hand-written
clients.
    
The changes in this patch make it possible to decode and encode JSON
arguments as action parameters and parts of response view models.

== Patch: ThreadLocal LdapContext limits number of LDAP connections to one per thread

During request processing, one LDAP connection per thread is
sufficient. The previous implementation could lead to LDAP connection
churning.

= Upstream repository

The original Apache git is mirrored on https://github.com/apache/isis[GitHub].

Many thanks to the Apache Isis people for their great work.

